### ISSUE TITLE
UI/UAT REVIEW - Login [with Whatsapp - Step 2]

### ISSUE THREAD

**Issue by inezamandha** [astrajingga/template-sirclo-driveOn#20]
### **UAT & UI Review - Login - with Whatsapp - Step 2**
Halo Astrajingga. Saya Inez ingin memberikan beberapa UAT & UI Review kembali yang sudah saya periksa terkait fitur di halaman **Login** pada bagian **Login with Whatsapp - Step 2**

---
**Link Figma**

https://www.figma.com/file/JPo41Y2Onymx35QQjykRTK/Template-Design---SIRCLO-2---Ongoing-Edit?node-id=212%3A4395

---
- [ ] **Button kembali ubah nomor**

Subtasks:
- [ ] Teks “Ubah Nomor” nya belum sesuai dengan Figma
- [ ] Poppins Medium 18px #444444

---
- [ ] **Title**

Subtasks:
- [ ] Seharusnya rata kiri
- [ ] Poppins bold 26px #333333

---
- [ ] **Kata Petunjuk**
Poppins 18px #444444

- [ ] **Button Kirim Kode OTP**

Subtasks:
- [ ] Seharusnya panjang buttonnya
- [ ] Border radius 8px
- [ ] Fontnya Poppins 18px

---
- [ ] **Bagian tidak memiliki whatsapp**

Subtasks:
- [ ] Poppins 14px #333333 untuk bagian “Tidak memiliki Whatsapp?”
- [ ] Untuk bagian login dengan metode lain harusnya lebih besar, jadi Poppins Bold 18px #E89F71

---
- [ ] **Mobile**
Disesuaikan dengan yang ada di desain. Sama seperti yang ada di desktop namun lebih diperbaiki font sizenya dan penempatannya

Staging:
<img width="212" alt="Mobile" src="https://user-images.githubusercontent.com/45808774/140260238-1ce975de-562a-4fd7-b248-0567eb62f0b1.png">

Figma:
<img width="141" alt="Mobile - Figma" src="https://user-images.githubusercontent.com/45808774/140260249-d077216f-0c46-41b2-b31c-7974249fb9db.png">

---
**Staging secara keseluruhan**
<img width="960" alt="Staging secara keseluruhan" src="https://user-images.githubusercontent.com/45808774/139833626-70b5c7e1-1c92-45c9-9619-087c894f80e1.png">

**Figma secara keseluruhan**
<img width="492" alt="Figma secara keseluruhan" src="https://user-images.githubusercontent.com/45808774/139833649-06c623af-9d8c-4b16-91b5-0150d9d575e5.png">
